---
mountOptions:
    btrfs:
        defaults: "defaults,compress=zstd,noatime"
    ext4:
        defaults: "defaults,noatime"
    xfs:
        defaults: "defaults,noatime"

efiMountPoint: "/boot/efi"
efiPartitionFsType: "vfat"

ssdExtraMountOptions:
    btrfs: "discard=async"
    ext4: "discard"
