---
# Locale module config

region: "America"
zone: "New_York"

tzone_data: "/usr/share/zoneinfo"

locales: "/usr/share/i18n/SUPPORTED"
localefile: "/etc/locale.gen"

geoip:
    style: "json"
    url: "https://geoip.kde.org/v1/calamares"
