---
# Partition module config

efiSystemPartition:       "/boot/efi"
efiSystemPartitionSize:   "300 MiB"
efiSystemPartitionName:   "EFI system partition"

ensureSuspendToDisk: true
neverCreateSwap: false

defaultFileSystemType: "btrfs"

availableFileSystemTypes:
    - btrfs

userSwapChoices:
    - none
    - suspend
    - file
    - partition

initialSwapChoice: none

allowManualPartitioning: true
showNotEncryptedBootMessage: true