---
# Partition module config

efiSystemPartition:       "/boot/efi"
efiSystemPartitionSize:   "300 MiB"
efiSystemPartitionName:   "EFI system partition"

ensureSuspendToDisk: true

defaultFsType: "ext4"

availableFsTypes:
    - ext4
    - btrfs
    - xfs
    - f2fs

allowManualPartitioning: true
showNotEncryptedBootMessage: true
