---
# Systemd services to enable in the installed system

services:
    - name: NetworkManager
      enabled: true
    - name: bluetooth
      enabled: true
    - name: cups
      enabled: true
    - name: avahi-daemon
      enabled: true
    - name: sddm
      enabled: true
    - name: fstrim.timer
      enabled: true

targets:
    - name: multi-user.target
      enabled: true
