---
# Unpackfs module - unpack squashfs to target

unpack:
    - source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
      sourcefs: "squashfs"
      destination: ""
      name: "Deploying Arch Linux base system"