---
# Users module config
defaultGroups:
    - name: users
      state: create
    - name: video
      state: create
    - name: wheel
      state: create
    - name: audio
      state: create
    - name: input
      state: create
    - name: power
      state: create
    - name: network
      state: create
    - name: storage  
    - name: lp
    - name: optical
    - name: i2c

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true

passwordRequirements:
    nonempty: true
    minLength: -1
    maxLength: -1
    libpwquality:
        - minlen=0
        - minclass=0

avatarFilePath: ~/.face
permitWeakPasswords: false
forbidBadPasswords: true

# CHANGE: Default to ZSH
userShell: /usr/bin/zsh