---
# Calamares Welcome module

showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false

requirements:
    requiredStorage: 20
    requiredRam: 2.0
    internetCheckUrl: https://archlinux.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen
    required:
        - storage
        - ram
        - root
