workspace = 1, layout:dwindle
workspace = 2, layout:dwindle
workspace = 3, layout:dwindle
workspace = 4, layout:dwindle
workspace = 5, layout:dwindle
workspace = 6, layout:dwindle
workspace = 7, layout:dwindle
workspace = 8, layout:dwindle
workspace = 9, layout:dwindle
workspace = 10, layout:dwindle
