# Calamares settings for Arch Linux Hyprland Dotfiles installer

modules-search: [ local, /usr/lib/calamares/modules ]

navigation-style: horizontal

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - luksbootkeyfile
    - users
    - removeuser
    - displaymanager
    - networkcfg
    - hwclock
    - packages
    - shellprocess
    - services-systemd
    - umount
  - show:
    - finished

branding: hyprland

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
