# Calamares settings for Mainstream Dotfiles installer

modules-search: [ /etc/calamares/modules, local, /usr/lib/calamares/modules ]

navigation-style: horizontal

instances:
  - id:     preinstall
    module: shellprocess
    config: preinstall.conf
  - id:     yay
    module: shellprocess
    config: yay.conf
  - id:     dotfiles
    module: shellprocess
    config: dotfiles.conf
  - id:     limine
    module: shellprocess
    config: limine.conf
  - id:     installgpudrivers
    module: shellprocess
    config: installgpudrivers.conf
  - id:     postinstall
    module: shellprocess
    config: postinstall.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - installchoice
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - luksbootkeyfile
    - users
    - removeuser
    - displaymanager
    - networkcfg
    - hwclock
    - shellprocess@preinstall
    - shellprocess@yay
    - shellprocess@dotfiles
    - shellprocess@limine
    - shellprocess@installgpudrivers
    - shellprocess@postinstall
    - packages
    - services-systemd
    - umount
  - show:
    - finished

branding: hyprland

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
