# hyprlang noerror false
# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = ~/.config/hypr/custom/scripts/bluetooth-autoconnect.sh
exec-once = /usr/local/bin/calamares-autostart
exec-once = /usr/local/bin/live-setup
exec-once = bash /etc/profile.d/dotfiles-first-login.sh
