# hyprlang noerror false

plugin {
    hyprbars {
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
	col.text = rgba(00000000)
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        hyprbars-button = rgba(49454e55), 13, 󰖭, hyprctl dispatch killactive, rgb(ffffff)
        hyprbars-button = rgba(49454e55), 13, 󰖯, hyprctl dispatch fullscreen 1, rgb(ffffff)
        hyprbars-button = rgba(49454e55), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special, rgb(ffffff)
    }
}
